# Site settings
title: CS231n Convolutional Neural Networks for Visual Recognition
email: karpathy@cs.stanford.edu
description: "Course materials and notes for Stanford class CS231n: Convolutional Neural Networks for Visual Recognition."
baseurl: ""
url: "http://cs231n.github.io"
twitter_username: cs231n
github_username:  cs231n

# Build settings
markdown: redcarpet
permalink: pretty
